apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ciskubebenchreports.aquasecurity.github.io
spec:
  group: aquasecurity.github.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
  scope: Cluster
  names:
    singular: ciskubebenchreport
    plural: ciskubebenchreports
    kind: CISKubeBenchReport
    listKind: CISKubeBenchReportList
    categories:
      - all
    shortNames:
      - kubebench
